#spring:
#  application:
  #    name: BOOKING-MS
#  datasource:
#    url: jdbc:h2:mem:booking
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 9110
#
#
##management:
##  tracing:
##    sampling:
##      probability: 1.0
#
##  zipkin:
##    tracing:
##      endpoint: http://localhost:9411/zipkin
#logging:
#  level:
#    root: debug
